"""
Pydantic schema for the final Structured Patient Profile.
This is the terminal output of the Clinical Text Agent pipeline.
"""

from pydantic import BaseModel, Field
from .clinical_entities import ClinicalEntities


class SourceMetadata(BaseModel):
    """Tracks which input source types were present in the current run."""

    doctor_notes: bool = False
    patient_conversation: bool = False
    health_records: bool = False


class StructuredPatientProfile(BaseModel):
    """
    Final output produced by the Clinical Text Agent.

    Contains:
    - clinical_entities  : structured JSON of extracted medical entities
    - medical_summary    : free-text summary generated by Medical T5
    - source_metadata    : flags indicating which input sources were used
    """

    clinical_entities: ClinicalEntities = Field(
        default_factory=ClinicalEntities,
        description="Unified clinical entities extracted from all inputs",
    )
    medical_summary: str = Field(
        default="",
        description="Concise patient summary generated by Medical T5",
    )
    source_metadata: SourceMetadata = Field(
        default_factory=SourceMetadata,
        description="Flags for each input source type present in this run",
    )
